# Copyright (c) 2019-2020 Cognizant Digital Business, Evolutionary AI. All rights reserved. Issued under the Apache 2.0 License.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: studioml-env
data:
  LOGXI_FORMAT: "happy,maxcol=1024"
  LOGXI: "*=DBG"
  QUEUE_MATCH: "^rmq_.*$"
  AMQP_URL: "amqp://guest:guest@rabbitmq-service:5672/"
  CLEAR_TEXT_MESSAGES: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: studioml-account
imagePullSecrets:
- name: studioml-go-docker-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: studioml-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studioml-role-bind
subjects:
- kind: ServiceAccount
  name: studioml-account
roleRef:
  kind: ClusterRole
  name: studioml-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  progressDeadlineSeconds: 360
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: studioml-account
      automountServiceAccountToken: true
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
          -name: RABBITMQ_ERLANG_COOKIE
           value: 'secret'
        resources:
          requests:
            memory: "3Gi"
            cpu: ".5"
          limits:
            memory: "3Gi"
            cpu: ".5"
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: client-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: admin-port
      protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studioml-go-runner-deployment
  labels:
    app: studioml-go-runner
spec:
  progressDeadlineSeconds: 360
  selector:
    matchLabels:
      app: studioml-go-runner
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: studioml-go-runner
    spec:
      serviceAccountName: studioml-account
      automountServiceAccountToken: true
      containers:
      - name: studioml-go-runner
        envFrom:
            - configMapRef:
                name: studioml-env
        image: docker.io/leafai/studio-go-runner:0.9.27-master-aaaagnrahyf
        imagePullPolicy: Always
        resources:
          requests:
            memory: "4Gi"
            cpu: "3"
          limits:
            memory: "4Gi"
            cpu: "3"
