dist: trusty
sudo: false

language: go

go:
  - 1.10.3

services:
  - docker

cache:
  directories:
  - docker

env:
    fast_finish: true  # Finish build earlier if it fails.  Not sure this has been implemented yet.

install:
  - go env
  - env | sort
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u -f github.com/karlmutch/duat/cmd/semver
  - go get -u -f github.com/karlmutch/duat/cmd/stencil
  - dep ensure
  - cd ./vendor/github.com/karlmutch/duat
  - pwd
  - cp ../../../../.travis-git.sh ./.travis-git.sh
  - source ./.travis-git.sh
    - git checkout -b feature/35_travis_and_git
    - git branch --set-upstream-to=origin/feature/35_travis_and_git feature/35_travis_and_git
    - git pull
    - git log | head
  - pwd
  - ls
  - ls cmd
  - ls semver
  - ls stencil
  - go install cmd/semver/semver.go
  - go install cmd/stencil/stencil.go
  - cd ../../../..

script:
  - pwd
  - ls
  - export GOBIN=$GOPATH/bin
  - go env
  - ./build.sh

notifications:
  email: false
  slack:
     rooms:
       secure: kgkdwmFp2ppCPH3LfWnybOjGtOvN9oKTyEol3chSCfN2/3ANc7xnWUBXNapgBQBIZcv/uEAPFa4jt8GSU3ZZUod75lNUl9W3iP27XMwq6VW5RanwmwI0zfTASoUIF0c9f5xejmgTb4NuYkaa8F61vmGZ9w2aSH7FEKnINfntI9zxIOngckn3UmcU9SxpBjvYRG8MfZJ13NCD87dM+doVDK2IYORXRzp2mh3NYkVepujRDgpM+nT19Naer8lYgfkEzbcFAWs1l8iboq+mUIUG2s+svAMiqa8Bae/PuyikAdYpY8wvbKxcpexCMCjjhFXuC02ABs80wgF5wzHXtFF9ZRNI9HngHwGahu0WzDaTWsMp8iPHxZGr2SY/8+phYcvs1qZ/JerYmI6cIBe66Wrg1hbsBafZ2PtXlPFVdO7Ojavz6Zv2uWwKtFphdahC96+j6tuf5wbDSHOGQIPRdYBjRF5rpbjTH+JAHI8YLz4PyS1NQr6uRwWUyiQ6EaEqjBT02qSxf1hKsz4/NtgIZ9NAuQq086wtRWb1/gkKuZm/EX0FihlsNMaTL9ZjEvpeotdZSUAiFUib6KoIlOV+FRgSgYjHG6DAKEDGKp7/OQeHzEigfnuRr0m2FLmK1ySHGSOatgVIS3o2v+9ZIrdBLuEvdQ/QMMH8OvE1/XlmDTWalf4=
