---
apiVersion: v1
kind: Namespace
metadata:
  name: makisu-cache
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: makisu-cache
  labels:
    redis: "true"
spec:
  containers:
  - name: main
    image: redis:6.0.1
    env:
      - name: MASTER
        value: "true"
      - name: DIR
        value: "/data"
    ports:
      - containerPort: 6379
    volumeMounts:
      - name: data
        mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: redis-cache-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cache-claim
  namespace: makisu-cache
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: makisu-cache
spec:
  selector:
    redis: "true"
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
