apiVersion: batch/v1
kind: Job
metadata:
  name: imagebuilder-stock
  namespace: {{ .Namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: makisu
        image: gcr.io/uber-container-tools/makisu:v0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - build
        - --push=quay.io
        - --modifyfs=true
        - -t=leafai/studio-go-runner:{{.duat.version}}
        - -f=Dockerfile.stock
        - --registry-config=/registry-config/registry.yaml
        - --redis-cache-addr=redis.makisu-cache.svc.cluster.local:6379
        - /makisu-context/cmd/runner
        volumeMounts:
        - name: context
          mountPath: /makisu-context
        - name: registry-config
          mountPath: /registry-config
        - name: storage
          mountPath: /makisu-storage
        resources:
          requests:
            ephemeral-storage: "15Gi"
          limits:
            ephemeral-storage: "15Gi"
      volumes:
      - name: context
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: build-pv-claim
      - name: registry-config
        secret:
          secretName: docker-registry-config
      - name: storage
        emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: imagebuilder-azure
  namespace: {{ .Namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: makisu
        image: gcr.io/uber-container-tools/makisu:v0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - build
        - --push=quay.io
        - --modifyfs=true
        - -t=leafai/azure-studio-go-runner:{{.duat.version}}
        - -f=Dockerfile.azure
        - --registry-config=/registry-config/registry.yaml
        - --redis-cache-addr=redis.makisu-cache.svc.cluster.local:6379
        - /makisu-context/cmd/runner
        volumeMounts:
        - name: context
          mountPath: /makisu-context
        - name: registry-config
          mountPath: /registry-config
        - name: storage
          mountPath: /makisu-storage
        resources:
          requests:
            ephemeral-storage: "25Gi"
          limits:
            ephemeral-storage: "25Gi"
      volumes:
      - name: context
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: build-pv-claim
      - name: registry-config
        secret:
          secretName: docker-registry-config
      - name: storage
        emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: imagebuilder-serving-bridge
  namespace: {{ .Namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: makisu
        image: gcr.io/uber-container-tools/makisu:v0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - build
        - --push=quay.io
        - --modifyfs=true
        - -t=leafai/studio-serving-bridge:{{.duat.version}}
        - -f=Dockerfile
        - --registry-config=/registry-config/registry.yaml
        - --redis-cache-addr=redis.makisu-cache.svc.cluster.local:6379
        - /makisu-context/tools/serving-bridge
        volumeMounts:
        - name: context
          mountPath: /makisu-context
        - name: registry-config
          mountPath: /registry-config
        - name: storage
          mountPath: /makisu-storage
        resources:
          requests:
            ephemeral-storage: "15Gi"
          limits:
            ephemeral-storage: "15Gi"
      volumes:
      - name: context
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: build-pv-claim
      - name: registry-config
        secret:
          secretName: docker-registry-config
      - name: storage
        emptyDir: {}
