version: "1.0"
stages:
  - "clone"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "leaf-ai/studio-go-runner"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
