
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
#
ignored = ["github.com/Sirupsen/logrus"]

[[override]]
  name = "github.com/Sirupsen/logrus"
  source = "github.com/sirupsen/logrus"

[[override]]
  name = "github.com/karlmutch/ccache"
  branch="master"

[[override]]
  name = "github.com/karlmutch/duat"
  branch="master"

[[override]]
  name = "gopkg.in/src-d/go-git.v4"
  version="v4.9.1"

# K8s API Version 1.10
[[override]]
  name = "github.com/ericchiang/k8s"
  version="v1.2.0"

[prune]
  go-tests = true
  unused-packages = true
