
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "2.x"
  name = "github.com/Masterminds/semver"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "1.11.1"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-radix"

[[constraint]]
  branch = "v2"
  name = "github.com/go-yaml/yaml"

[[constraint]]
  name = "github.com/golang/dep"
  version = "0.2.0"

[[constraint]]
  name = "github.com/mgutz/logxi"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/nightlyone/lockfile"

[[constraint]]
  branch = "master"
  name = "github.com/pelletier/go-toml"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/sdboyer/constext"
