# Copyright (c) 2019-2020 Cognizant Digital Business, Evolutionary AI. All rights reserved. Issued under the Apache 2.0 License.
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: studioml-go-runner-ecr-cred
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: studioml-go-runner-ecr-cred
            command:
            - /bin/sh
            - -c
            - |-
              TOKEN=`aws ecr get-login --region {{expandenv "$AWS_REGION"}} --registry-ids {{expandenv "$AWS_ACCOUNT"}} | cut -d' ' -f6`
              echo "ENV variables setup done."
              kubectl delete secret --ignore-not-found studioml-go-docker-key
              kubectl create secret docker-registry studioml-go-docker-key \
              --docker-server=https://{{expandenv "$AWS_ACCOUNT"}}.dkr.ecr.{{expandenv "$AWS_REGION"}}.amazonaws.com \
              --docker-username={{expandenv "$AWS_ACCOUNT"}} \
              --docker-password="${TOKEN}" \
              --docker-email="{{expandenv "$EMAIL"}}"
              echo "Secret created by name. studioml-go-docker-key"
              kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"'studioml-go-docker-key'"}]}'
              echo "All done."
            env:
            - name: AWS_DEFAULT_REGION
              value: {{expandenv "$AWS_REGION"}}
            - name: AWS_ACCESS_KEY_ID
              value: {{expandenv "$AWS_ACCESS_KEY"}}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{expandenv "$AWS_SECRET_ACCESS_KEY"}}
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            resources: {}
            securityContext:
              capabilities: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: Default
          hostNetwork: true
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: studioml-env
data:
 LOGXI_FORMAT: "happy,maxcol=1024"
 LOGXI: "*=DBG"
 QUEUE_MATCH: "^sqs_.*$"
 SQS_CERTS: "./certs/aws-sqs"
 MESSAGE_CRYPT: "./certs/message"
 CACHE_SIZE: "10Gib"
 CACHE_DIR: "/tmp/cache"
 CLEAR_TEXT_MESSAGES: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: studioml-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: studioml-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studioml-role-bind
subjects:
- kind: ServiceAccount
  name: studioml-account
roleRef:
  kind: ClusterRole
  name: studioml-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: studioml-go-runner-deployment
 labels:
   app: studioml-go-runner
spec:
 progressDeadlineSeconds: 360
 selector:
   matchLabels:
     app: studioml-go-runner
 replicas: 1
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: studioml-go-runner
   spec:
      serviceAccountName: studioml-account
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: studioml-go-docker-key
      containers:
      - name: studioml-go-runner
        envFrom:
        - configMapRef:
            name: studioml-env
        image: {{expandenv "$AWS_IMAGE"}}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - name: aws-sqs
          mountPath: "/runner/certs/aws-sqs/default"
          readOnly: true
        - name: message-encryption
          mountPath: "/runner/certs/message/encryption"
          readOnly: true
        - name: encryption-passphrase
          mountPath: "/runner/certs/message/passphrase"
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
        - name: nvidia
          mountPath: /usr/local/nvidia
        - name: libcuda
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: aws-sqs
          secret:
            optional: true
            secretName: studioml-runner-aws-sqs
            items:
            - key: credentials
              path: credentials
            - key: config
              path: config
        - name: message-encryption
          secret:
            optional: false
            secretName: studioml-runner-key-secret
            items:
            - key: ssh-privatekey
              path: ssh-privatekey
            - key: ssh-publickey
              path: ssh-publickey
        - name: encryption-passphrase
          secret:
            optional: false
            secretName: studioml-runner-passphrase-secret
            items:
            - key: ssh-passphrase
              path: ssh-passphrase
        - name: tmp-volume
          awsElasticBlockStore:
            volumeID: {{expandenv "$AWS_VOLUME_ID"}}
            fsType: ext4
        - name: nvidia
          hostPath:
            path: /usr/local/nvidia
        - name: libcuda
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
