# Copyright (c) 2019-2020 Cognizant Digital Business, Evolutionary AI. All rights reserved. Issued under the Apache 2.0 License.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: studioml-env
data:
  LOGXI_FORMAT: "happy,maxcol=1024"
  LOGXI: "*=DBG"
  SQS_CERTS: "certs/aws-sqs"
  MESSAGE_CRYPT: "certs/message"
  QUEUE_MATCH: "^rmq_.*$"
  AMPQ_URL: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: studioml-account
imagePullSecrets:
- name: studioml-go-docker-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: studioml-role
rules:
- apiGroups:
  - "*"
  resources:
  - configMaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studioml-role-bind
subjects:
- kind: ServiceAccount
  name: studioml-account
roleRef:
  kind: ClusterRole
  name: studioml-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studioml-go-runner-deployment
  labels:
    app: studioml-go-runner
spec:
  progressDeadlineSeconds: 360
  selector:
    matchLabels:
      app: studioml-go-runner
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: studioml-go-runner
    spec:
      serviceAccountName: studioml-account
      automountServiceAccountToken: false
      containers:
      - name: studioml-go-runner
        envFrom:
            - configMapRef:
                name: studioml-env
        image: studioml/studio-go-runner
        #image: {{ expandenv "$azure_registry_name"}}.azurecr.io/{{ expandenv "$azure_registry_name"}}/{{.duat.module}}:{{.duat.version}}
        #image: nvidia/cuda:8.0-cudnn7-runtime-ubuntu16.04
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "10Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - name: aws-sqs
          mountPath: "/runner/certs/aws-sqs/default"
          readOnly: true
        - name: message-encryption
          mountPath: "/runner/certs/message/encryption"
          readOnly: true
        - name: encryption-passphrase
          mountPath: "/runner/certs/message/passphrase"
          readOnly: true
      imagePullSecrets:
        - name: studioml-go-docker-key
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: tmp-volume
          emptyDir:
            sizeLimit: 80Gi
        - name: aws-sqs
          secret:
            optional: true
            secretName: studioml-runner-aws-sqs
            items:
            - key: credentials
              path: credentials
            - key: config
              path: config
        - name: message-encryption
          secret:
            optional: false
            secretName: studioml-runner-key-secret
            items:
            - key: ssh-privatekey
              path: ssh-privatekey
            - key: ssh-publickey
              path: ssh-publickey
        - name: encryption-passphrase
          secret:
            optional: false
            secretName: studioml-runner-passphrase-secret
            items:
            - key: ssh-passphrase
              path: ssh-passphrase
