---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: studioml-go-runner
spec:
  selector:
    matchLabels:
      app: studioml-go-runner
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: studioml-go-runner
    spec:
      containers:
      - name: studioml-go-runner
        image: sentientai.azurecr.io/sentient.ai/studio-go-runner:<repo-version></repo-version>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
        volumeMounts:
        - name: google-cert
          mountPath: "/runner/certs/google.json"
          readOnly: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
      - name: google-cert
        secret:
          secretName: studioml-runner-cert
