apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: studioml-go-runner-deployment
  labels:
    app: studioml-go-runner
spec:
  progressDeadlineSeconds: 360
  selector:
    matchLabels:
      app: studioml-go-runner
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: studioml-go-runner
    spec:
      imagePullSecrets:
        - name: studioml-go-docker-key
      containers:
      - name: studioml-go-runner
        image: {{ expandenv "$azure_registry_name" }}.azurecr.io/sentient.ai/{{.duat.module}}/runner:{{.duat.version}}
        imagePullPolicy: Always
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
            memory: "50Gi"
            cpu: "4"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: aws-sqs
          mountPath: "/runner/certs/aws-sqs/default"
          readOnly: true
        - name: nvidia
          mountPath: /usr/local/nvidia
        - name: libcuda
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: tmp-volume
          emptyDir:
            sizeLimit: 80Gi
        - name: aws-sqs
          secret:
            optional: true
            secretName: studioml-runner-aws-sqs
            items:
            - key: credentials
              path: credentials
            - key: config
              path: config
        - name: nvidia
          hostPath:
            path: /usr/local/nvidia
        - name: libcuda
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/libcuda.so.1

