# Copyright (c) 2019-2020 Cognizant Digital Business, Evolutionary AI. All rights reserved. Issued under the Apache 2.0 License.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: studioml-env
data:
  LOGXI_FORMAT: "happy,maxcol=1024"
  LOGXI: "*=DBG"
  QUEUE_MATCH: "^rmq_.*$"
  AMQP_URL: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: studioml-account
imagePullSecrets:
- name: studioml-go-docker-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: studioml-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studioml-role-bind
subjects:
- kind: ServiceAccount
  name: studioml-account
roleRef:
  kind: ClusterRole
  name: studioml-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studioml-go-runner-deployment
  labels:
    app: studioml-go-runner
spec:
  progressDeadlineSeconds: 360
  selector:
    matchLabels:
      app: studioml-go-runner
  replicas: 20
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: studioml-go-runner
    spec:
      serviceAccountName: studioml-account
      automountServiceAccountToken: true
      containers:
      - name: studioml-go-runner
        envFrom:
            - configMapRef:
                name: studioml-env
        image: studioml/studio-go-runner
        #image: {{ expandenv "$azure_registry_name"}}.azurecr.io/{{ expandenv "$azure_registry_name"}}/{{.duat.module}}:{{.duat.version}}
        #image: nvidia/cuda:8.0-cudnn7-runtime-ubuntu16.04
        imagePullPolicy: Always
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "40Gi"
            cpu: "5"
          limits:
            nvidia.com/gpu: 1
            memory: "40Gi"
            cpu: "5"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
          #- mountPath: /usr/local/nvidia
          #name: nvidia
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: tmp-volume
          emptyDir:
            sizeLimit: 80Gi
