# Copyright (c) 2019-2021 Cognizant Digital Business, Evolutionary AI. All rights reserved. Issued under the Apache 2.0 License.
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: studioml-go-runner-ecr-cred
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: studioml-go-runner-ecr-cred
            command:
            - /bin/sh
            - -c
            - |-
              ACCOUNT={{ expandenv "$AWS_ACCOUNT" }}
              REGION={{ expandenv "$AWS_DEFAULT_REGION" }}
              SECRET_NAME=studioml-go-docker-key
              EMAIL=[email address]
              TOKEN=`aws ecr get-login --region ${REGION} --registry-ids ${ACCOUNT} | cut -d' ' -f6`
              echo "ENV variables setup done."
              kubectl delete secret --ignore-not-found $SECRET_NAME
              kubectl create secret docker-registry $SECRET_NAME \
              --docker-server=https://${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com \
              --docker-username=AWS \
              --docker-password="${TOKEN}" \
              --docker-email="${EMAIL}"
              echo "Secret created by name. $SECRET_NAME"
              kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"'$SECRET_NAME'"}]}'
              echo "All done."
            env:
            - name: AWS_DEFAULT_REGION
              value:{{ expandenv "$AWS_DEFAULT_REGION" }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ expandenv "$AWS_ACCESS_KEY_ID" }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ expandenv "$AWS_SECRET_ACCESS_KEY" }}
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            resources: {}
            securityContext:
              capabilities: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: Default
          hostNetwork: true
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: studioml-env
data:
 LOGXI_FORMAT: "happy,maxcol=1024"
 LOGXI: "*=DBG"
 QUEUE_MATCH: "^sqs_StudioML_.*$"
 SQS_CERTS: "./certs/aws-sqs"
 MESSAGE_CRYPT: "./certs/message"
 CACHE_SIZE: "10Gib"
 CACHE_DIR: "/tmp/cache"
 CLEAR_TEXT_MESSAGES: "true"
 LIMIT_IDLE_DURATION: "15m"
 DISABLED_LIMIT_TASKS: "1"
 ALLOW_ENV_SECRETS: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: studioml-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: studioml-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studioml-role-bind
subjects:
- kind: ServiceAccount
  name: studioml-account
roleRef:
  kind: ClusterRole
  name: studioml-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: studioml-signing
type: Opaque
data:
  info: RHVtbXkgU2VjcmV0IHNvIHJlc291cmNlIHJlbWFpbnMgcHJlc2VudA==
---
apiVersion: v1
kind: Secret
metadata:
  name: studioml-report-keys
type: Opaque
data:
  info: RHVtbXkgU2VjcmV0IHNvIHJlc291cmNlIHJlbWFpbnMgcHJlc2VudA==
---
apiVersion: batch/v1
kind: Job
metadata:
 name: studioml-go-runner
spec:
 parallelism: 1
 backoffLimit: 2
 template:
   spec:
      restartPolicy: Never
      serviceAccountName: studioml-account
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: studioml-go-docker-key
      containers:
      - name: studioml-go-runner
        env:
          - name: AWS_DEFAULT_REGION
            value:{{ expandenv "$AWS_DEFAULT_REGION" }}
          - name: AWS_ACCESS_KEY_ID
            value: {{ expandenv "$AWS_ACCESS_KEY_ID" }}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ expandenv "$AWS_SECRET_ACCESS_KEY" }}
        envFrom:
        - configMapRef:
            name: studioml-env
        #  Digest should be used to prevent version drift, prevented using idempotent SHA256 digest
        image: quay.io/leafai/studio-go-runner:0.13.2-main-aaaagqrvxyo
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "2"
        volumeMounts:
        - name: aws-sqs
          mountPath: "/runner/certs/aws-sqs/default"
          readOnly: true
        - name: message-encryption
          mountPath: "/runner/certs/message/encryption"
          readOnly: true
        - name: encryption-passphrase
          mountPath: "/runner/certs/message/passphrase"
          readOnly: true
        - name: queue-signing
          mountPath: "/runner/certs/queues/signing"
          readOnly: true
        - name: response-queue-signing
          mountPath: "/runner/certs/queues/response-encrypt"
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
        - name: nvidia
          mountPath: /usr/local/nvidia
        - name: libcuda
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: aws-sqs
          secret:
            optional: true
            secretName: studioml-runner-aws-sqs
            items:
            - key: credentials
              path: credentials
            - key: config
              path: config
        - name: message-encryption
          secret:
            optional: true
            secretName: studioml-runner-key-secret
            items:
            - key: ssh-privatekey
              path: ssh-privatekey
            - key: ssh-publickey
              path: ssh-publickey
        - name: encryption-passphrase
          secret:
            optional: true
            secretName: studioml-runner-passphrase-secret
            items:
            - key: ssh-passphrase
              path: ssh-passphrase
        - name: queue-signing
          secret:
            optional: false
            secretName: studioml-signing
        - name: response-queue-signing
          secret:
            optional: false
            secretName: studioml-report-keys
        - name: tmp-volume
          emptyDir:
            sizeLimit: 200Gi
        - name: nvidia
          hostPath:
            path: /usr/local/nvidia
        - name: libcuda
          hostPath:
            path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
