# Copyright (c) 2020 Cognizant Digital Business, Evolutionary AI. All rights reserved. Issued under the Apache 2.0 License.
---
apiVersion: v1
kind: Namespace
metadata:
  name: serving-bridge
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: serving-bridge-env
  namespace: serving-bridge
data:
  LOGXI_FORMAT: "happy,maxcol=1024"
  LOGXI: "*=DBG"
  TFX_CONFIG_MAP_NAME: "tfx-config"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tfx-config
  namespace: serving-bridge
data:
  tfx-config: "model_config_list: {}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serving-bridge-account
  namespace: serving-bridge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serving-bridge-role
  namespace: serving-bridge
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serving-bridge-role-bind
  namespace: serving-bridge
subjects:
- kind: ServiceAccount
  name: serving-bridge-account
roleRef:
  kind: ClusterRole
  name: serving-bridge-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-bridge-deployment
  namespace: serving-bridge
  labels:
    app: serving-bridge
spec:
 progressDeadlineSeconds: 360
 selector:
   matchLabels:
     app: serving-bridge
 replicas: 1
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: serving-bridge
   spec:
      serviceAccountName: serving-bridge-account
      automountServiceAccountToken: true
      containers:
      - name: serving-bridge
        envFrom:
        - configMapRef:
            name: serving-bridge-env
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: credentials
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: credentials
                key: aws_secret_access_key
          - name: AWS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: credentials
                key: aws_endpoint
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: credentials
                key: aws_region
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: credentials
                key: aws_bucket
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: quay.io/leafai/studio-serving-bridge
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: false
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "namespace"
                fieldRef:
                  fieldPath: metadata.namespace
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
