apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfx-serving
  namespace: serving-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfx-serving
  template:
    metadata:
      labels:
        app: tfx-serving
    spec:
      serviceAccountName: serving-bridge-account
      containers:
        - name: tfx-serving
          image: tensorflow/serving
          command:
          - /usr/bin/tensorflow_model_server
          args:
          - --port=8500
          - --rest_api_port=8501
          - --model_config_file=/mnt/tfx-config
          - --model_config_file_poll_wait_seconds=60
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: 8500
          ports:
            - containerPort: 8501
              name: restapi
            - containerPort: 8500
              name: grpc
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: credentials
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: credentials
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                key: AWS_REGION
                name: credentials
          - name: TF_CPP_MIN_LOG_LEVEL
            value: "2"
          - name: S3_USE_HTTPS
            value: "false"
          - name: S3_VERIFY_SSL
            value: "false"
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: AWS_ENDPOINT
                name: credentials
          volumeMounts:
          - mountPath: /mnt
            name: config-volume
      volumes:
      - configMap:
          name: tfx-config
        name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: serving
  name: serving
  namespace: serving-bridge
spec:
  ports:
    - port: 8501
      targetPort: 8501
      name: restapi
    - port: 8500
      targetPort: 8500
      name: grpc
  selector:
    app: serving
  type: LoadBalancer
